INSERT INTO Categories (CategoryName) VALUES ('Food');
INSERT INTO Categories (CategoryName) VALUES ('Historic sites');
INSERT INTO Categories (CategoryName) VALUES ('Night Life');
INSERT INTO Categories (CategoryName) VALUES ('Attractions');


INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('La Sqala', 0, 'Typical Moroccan food in a Portuguaise castle',0,0,'/Images/Food/La Sqala.jpg','Food');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Ricks cafe', 0, 'Inspired by the Holywood film Casablanca. Rick’s Café is a restaurant, bar and café located in the city of Casablanca, Morocco.',0,0,'/Images/Food/Ricks cafe.jpg','Food');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Blend', 0, 'Homemade burgers in the vibrant quarter of Casablanca',0,0,'/Images/Food/Blend.jpg','Food');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Le SOC', 0, 'One of the few great Kosher restaurants in the city',0,0,'/Images/Food/Le Soc.jpg','Food');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Le Petit Rocher', 0, 'Have a lovely dinner with a view over the coast of the Atlantic Ocean.',0,0,'/Images/Food/Le Petit Rocher.jpg','Food');

INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Hassan II Mosque', 0, 'A breathtaking mosque partly resides by the sea with the tallest minaret in the world.',0,0,'/Images/History/Hassan Mosque.jpg','Historic sites');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Habous', 0, 'Enjoy a walk in the French Medina which neighbours the royal palace.',0,0,'/Images/History/Habous.jpg','Historic sites');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('The market', 0, 'A good place to buy souvenirs and enjoy a cup of mint tea.',0,0,'/Images/History/The market.jpg','Historic sites');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Beth El synagogue', 0, 'Built in 1948, this synagogue can host over 3000 believers. One of the largest temples in the country.',0,0,'/Images/History/Beth El.jpg','Historic sites');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Slaoui museum', 0, 'A 1940s Art Deco villa which consists of different collections varying from Orientalist posters to Berber jewelry.',0,0,'/Images/History/Slaoui Museum.jpg','Historic sites');

INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Balcony 33', 0, 'Enjoy a peaceful and lovely evening with great music and service.',0,0,'/Image/Night Life/Balcony 33.jpg','Night Life');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Flamingo beach club', 0, 'Between dream and reality, there is the Flamingo Beach Club that will make you dream with your eyes open.',0,0,'/Image/Night Life/Flamingo Beach Club.jpg','Night Life');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Tahiti beach club', 0, 'This famous beach offers three restaurants, two swimming pools, a gym, a spa, a kids club and a surf school',0,0,'/Image/Night Life/Tahiti Beach Club.jpg','Night Life');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('La Bodega', 0, 'One of best places to have good drinks and enjoy latino music in Casablanca, Morocco.',0,0,'/Image/Night Life/La Bodega.png','Night Life');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Sky 28', 0, 'Located the 28th floor, the SKY 28 offers the most beautiful view possible of the white city.',0,0,'/Image/Night Life/Sky 28.jpg','Night Life');

INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Morocco mall', 0, 'One of the largest malls in the world. One of its famous attractions is the dancing fountain and the aquarium.',0,0,'/Image/Attractions/Morocco Mall.jpeg','Attractions');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Ain Diab Surf School', 0, 'Spend a few hours surfing the high waves of the Atlantic Ocean.',0,0,'/Image/Attractions/Ain Diab Surf School.jpg','Attractions');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Sindibad Park', 0, 'This amusement park is a fun attraction for both adults and children. Dont forget to visit the zoo inside the park!',0,0,'/Image/Attractions/Sindibad.jpg','Attractions');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Anfa place', 0, 'A shopping center and a pleasant and convenient invitation for an easy and complete shopping experience.',0,0,'/Image/Attractions/Anfa Place.jpg','Attractions');
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category) VALUES ('Untied nations square', 0, 'A vibrant square that hosts public events, exhibitions and concerts.',0,0,'/Image/Attractions/United Nations Square.jpg','Attractions');