INSERT INTO Categories (CategoryName) VALUES ('Food');
INSERT INTO Categories (CategoryName) VALUES ('Historic sites');
INSERT INTO Categories (CategoryName) VALUES ('Night Life');
INSERT INTO Categories (CategoryName) VALUES ('Attractions');


INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('La Sqala', 0, 'Typical Moroccan food in a Portuguaise castle',0,0,'/Images/Food/La Sqala.jpg','Food', 33.602898,-7.619122000000061);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Ricks cafe', 0, 'Inspired by the Holywood film Casablanca. Rick’s Café is a restaurant, bar and café located in the city of Casablanca, Morocco.',0,0,'/Images/Food/Ricks cafe.jpg','Food', 33.605208,-7.62039900000002);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Blend', 0, 'Homemade burgers in the vibrant quarter of Casablanca',0,0,'/Images/Food/Blend.jpg','Food',33.588644,-7.631875000000036);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Le SOC', 0, 'One of the few great Kosher restaurants in the city',0,0,'/Images/Food/Le Soc.jpg','Food', 33.5312152, -7.674566599999935);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Le Petit Rocher', 0, 'Have a lovely dinner with a view over the coast of the Atlantic Ocean.',0,0,'/Images/Food/Le Petit Rocher.jpg','Food',33.609384,-7.651409999999942);

INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Hassan II Mosque', 0, 'A breathtaking mosque partly resides by the sea with the tallest minaret in the world.',0,0,'/Images/History/Hassan Mosque.jpg','Historic sites',33.6084136,-7.632757500000025);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Habous', 0, 'Enjoy a walk in the French Medina which neighbours the royal palace.',0,0,'/Images/History/Habous.jpg','Historic sites', 33.5778581,-7.610066200000006);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('The market', 0, 'A good place to buy souvenirs and enjoy a cup of mint tea.',0,0,'/Images/History/The market.jpg','Historic sites',33.5952823,-7.623395899999991);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Beth El synagogue', 0, 'Built in 1948, this synagogue can host over 3000 believers. One of the largest temples in the country.',0,0,'/Images/History/Beth El.jpg','Historic sites', 33.5960439,-7.6281668999999965);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Slaoui museum', 0, 'A 1940s Art Deco villa which consists of different collections varying from Orientalist posters to Berber jewelry.',0,0,'/Images/History/Slaoui Museum.jpg','Historic sites', 33.5924373,-7.62257939999995);

INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Balcony 33', 0, 'Enjoy a peaceful and lovely evening with great music and service.',0,0,'/Images/Night Life/Balcony 33.jpg','Night Life',33.5959741,-7.67535369999996);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Flamingo beach club', 0, 'Between dream and reality, there is the Flamingo Beach Club that will make you dream with your eyes open.',0,0,'/Images/Night Life/Flamingo Beach Club.jpg','Night Life',33.5868651,-7.685990299999958);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Tahiti beach club', 0, 'This famous beach offers three restaurants, two swimming pools, a gym, a spa, a kids club and a surf school',0,0,'/Images/Night Life/Tahiti Beach Club.jpg','Night Life',33.5970743,-7.6732935);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('La Bodega', 0, 'One of best places to have good drinks and enjoy latino music in Casablanca, Morocco.',0,0,'/Images/Night Life/La Bodega.png','Night Life',33.59537,-7.611673999999994);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Sky 28', 0, 'Located the 28th floor, the SKY 28 offers the most beautiful view possible of the white city.',0,0,'/Images/Night Life/Sky 28.jpg','Night Life',33.586646,-7.632010400000013);

INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Morocco mall', 0, 'One of the largest malls in the world. One of its famous attractions is the dancing fountain and the aquarium.',0,0,'/Images/Attractions/Morocco Mall.jpeg','Attractions',33.5758954,-7.706820999999991);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Ain Diab Surf School', 0, 'Spend a few hours surfing the high waves of the Atlantic Ocean.',0,0,'/Images/Attractions/Ain Diab Surf School.jpg','Attractions',33.5844067,-7.691259500000001);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Sindibad Park', 0, 'This amusement park is a fun attraction for both adults and children. Dont forget to visit the zoo inside the park!',0,0,'/Images/Attractions/Sindibad.jpg','Attractions',33.582292,-7.694402999999966);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Anfa place', 0, 'A shopping center and a pleasant and convenient invitation for an easy and complete shopping experience.',0,0,'/Images/Attractions/Anfa Place.jpg','Attractions',33.59816,-7.6646601999999575);
INSERT INTO POI (POI_name, NumOfViews, POI_description,POI_rank, NumOfRanks, PicturePath, Category, Latitude, Longitude) VALUES ('Untied nations square', 0, 'A vibrant square that hosts public events, exhibitions and concerts.',0,0,'/Images/Attractions/United Nations Square.jpg','Attractions',33.5953159,-7.618063600000028);